// DO NOT EDIT THIS FILE. EDIT strings.json then run python StringsConverter.py

@import Foundation;
NS_ASSUME_NONNULL_BEGIN
/** "About", Title for the about page */
FOUNDATION_EXPORT NSString* ABOUT_STRING();
/** "About This Version", Label for button to show version numbers and licenses */
FOUNDATION_EXPORT NSString* ABOUT_VERSION_STRING();
/** "Accounts", Title for the accounts tab */
FOUNDATION_EXPORT NSString* ACCOUNTS_STRING();
/** "Account", The string describing a buddy's account */
FOUNDATION_EXPORT NSString* ACCOUNT_STRING();
/** "Active", segmented control value for active friends */
FOUNDATION_EXPORT NSString* ACTIVE_BUDDIES_STRING();
/** "Active", This will be displayed in the UI as 'Active 10m ago'  */
FOUNDATION_EXPORT NSString* ACTIVE_STRING();
/** "Add Buddy", The title for the view to add a buddy */
FOUNDATION_EXPORT NSString* ADD_BUDDY_STRING();
/** "Add Existing Account", Label for button to create account by logging into an existing account */
FOUNDATION_EXPORT NSString* ADD_EXISTING_STRING();
/** "Is %@ your friend? Add him/her to auto-download pictures in the future.", Shown in chat view to prompt user to add friend for auto-download of group media messages. */
FOUNDATION_EXPORT NSString* ADD_FRIEND_TO_AUTO_DOWNLOAD();
/** "Add", Button title to add someone as a buddy */
FOUNDATION_EXPORT NSString* ADD_STRING();
/** "Advanced", String to describe advanced set of settings */
FOUNDATION_EXPORT NSString* ADVANCED_STRING();
/** "Restore iTunes backups to new devices", Description for allowing DB passphrase backup */
FOUNDATION_EXPORT NSString* ALLOW_DB_PASSPHRASE_BACKUP_DESCRIPTION_STRING();
/** "Allow Device Migration", Title for allowing DB passphrase backup */
FOUNDATION_EXPORT NSString* ALLOW_DB_PASSPHRASE_BACKUP_TITLE_STRING();
/** "Archive", Verb. action for archiving an old conversation */
FOUNDATION_EXPORT NSString* ARCHIVE_ACTION_STRING();
/** "Archive", Noun. segmented control value for displaying archived conversations */
FOUNDATION_EXPORT NSString* ARCHIVE_STRING();
/** "Are you sure?", Shown to confirm destructive actions */
FOUNDATION_EXPORT NSString* ARE_YOU_SURE_STRING();
/** "Audio Message", Text for media message summary */
FOUNDATION_EXPORT NSString* AUDIO_MESSAGE_STRING();
/** "Automatic Downloads Disabled", error */
FOUNDATION_EXPORT NSString* AUTOMATIC_DOWNLOADS_DISABLED_STRING();
/** "Automatically Fetch Media", Title for other miscellaneous settings group */
FOUNDATION_EXPORT NSString* AUTO_URL_FETCH_STRING();
/** "All incoming messages containing URLs will be fetched by default to show a media preview. This is required for media messaging to work properly. Disable this if you do not trust your contacts.", Title for other miscellaneous settings group */
FOUNDATION_EXPORT NSString* AUTO_URL_FETCH_WARNING_STRING();
/** "Available", Label in buddy list for users that are available */
FOUNDATION_EXPORT NSString* AVAILABLE_STRING();
/** "Away", Label in buddy list for users that are away */
FOUNDATION_EXPORT NSString* AWAY_STRING();
/** "Don't change these unless you really know what you're doing. By default we will always select the best available encryption method.",  */
FOUNDATION_EXPORT NSString* Advanced_Crypto_Warning();
/** "Advanced Encryption Settings",  */
FOUNDATION_EXPORT NSString* Advanced_Encryption_Settings();
/** "Basic", string to describe basic set of settings */
FOUNDATION_EXPORT NSString* BASIC_STRING();
/** "Block & Remove", The String for a buddy to block and remove a buddy from the buddy list */
FOUNDATION_EXPORT NSString* BLOCK_AND_REMOVE_STRING();
/** "Block", The String for a button to block a buddy */
FOUNDATION_EXPORT NSString* BLOCK_STRING();
/** "You and %@ are now friends.", Notification message when buddy has approved you */
FOUNDATION_EXPORT NSString* BUDDY_APPROVED_STRING();
/** "Buddy Info", The title for the view that shows detailed buddy info */
FOUNDATION_EXPORT NSString* BUDDY_INFO_STRING();
/** "Basic Setup", username section */
FOUNDATION_EXPORT NSString* Basic_Setup();
/** "Think of a unique nickname that you don't use anywhere else and doesn't contain personal information.", basic setup selection footer */
FOUNDATION_EXPORT NSString* Basic_Setup_Hint();
/** "Best Available",  */
FOUNDATION_EXPORT NSString* Best_Available();
/** "Cancel", Cancel an alert window */
FOUNDATION_EXPORT NSString* CANCEL_STRING();
/** "ChatSecure Push", Title for ChatSecure Push (this probably doesnt need to be translated) */
FOUNDATION_EXPORT NSString* CHATSECURE_PUSH_STRING();
/** "Chats", Title for chats view */
FOUNDATION_EXPORT NSString* CHATS_STRING();
/** "Chat", Title for chat view */
FOUNDATION_EXPORT NSString* CHAT_STRING();
/** "Compose", Label for text field where you compose a new message */
FOUNDATION_EXPORT NSString* COMPOSE_STRING();
/** "Connected", Whether or not account is logged in */
FOUNDATION_EXPORT NSString* CONNECTED_STRING();
/** "Connecting", String to state if an account is progress of creating a connection */
FOUNDATION_EXPORT NSString* CONNECTING_STRING();
/** "Connecting to Tor", Message shown when connecting to the Tor network */
FOUNDATION_EXPORT NSString* CONNECTING_TO_TOR_STRING();
/** "Please re-verify the server's certificate.", alert title for connection errors */
FOUNDATION_EXPORT NSString* CONNECTION_ERROR_CERTIFICATE_VERIFY_STRING();
/** "There was an error connecting to account", alert title for connection errors */
FOUNDATION_EXPORT NSString* CONNECTION_ERROR_STRING();
/** "Connect", String for button to connect connect */
FOUNDATION_EXPORT NSString* CONNECT_STRING();
/** "Copy Link", Copy link URL to clipboard as in copy and paste */
FOUNDATION_EXPORT NSString* COPY_LINK_STRING();
/** "Copy", Copy string to clipboard as in copy and paste */
FOUNDATION_EXPORT NSString* COPY_STRING();
/** "Could not parse URL.", Error description */
FOUNDATION_EXPORT NSString* COULD_NOT_PARSE_URL_STRING();
/** "Created by", Start of sentence that will be followed by names */
FOUNDATION_EXPORT NSString* CREATED_BY_STRING();
/** "Create New Account", Label for button to create a new account via in band registration */
FOUNDATION_EXPORT NSString* CREATE_NEW_ACCOUNT_STRING();
/** "Create", Title for button to create account */
FOUNDATION_EXPORT NSString* CREATE_STRING();
/** "Creating Account", Title for progress of creating a new account */
FOUNDATION_EXPORT NSString* CREATING_ACCOUNT_STRING();
/** "Custom", Place holder label for custom domains */
FOUNDATION_EXPORT NSString* CUSTOM_STRING();
/** "Choose Server", title for server selection screen */
FOUNDATION_EXPORT NSString* Choose_Server_String();
/** "Could not decrypt database. If the app is not working properly, you may need to delete and reinstall.",  */
FOUNDATION_EXPORT NSString* Could_Not_Decrypt_Database();
/** "The app crashed last time it was launched. Send a crash report?",  */
FOUNDATION_EXPORT NSString* Crash_Detected_Message();
/** "Crash Detected",  */
FOUNDATION_EXPORT NSString* Crash_Detected_Title();
/** "Customize Username", if you want to change your username */
FOUNDATION_EXPORT NSString* Customize_Username();
/** "Deactivate", e.g. for deactivating your push account */
FOUNDATION_EXPORT NSString* DEACTIVATE_STRING();
/** "Delete Account", Button to delete account */
FOUNDATION_EXPORT NSString* DELETE_ACCOUNT_BUTTON_STRING();
/** "Permanently delete", Ask user if they want to delete the stored account information */
FOUNDATION_EXPORT NSString* DELETE_ACCOUNT_MESSAGE_STRING();
/** "Delete Account?", Ask user if they want to delete the stored account information */
FOUNDATION_EXPORT NSString* DELETE_ACCOUNT_TITLE_STRING();
/** "Delete chats on disconnect", Description for automatic conversation deletion */
FOUNDATION_EXPORT NSString* DELETE_CONVERSATIONS_ON_DISCONNECT_DESCRIPTION_STRING();
/** "Auto-delete", Title for automatic conversation deletion setting */
FOUNDATION_EXPORT NSString* DELETE_CONVERSATIONS_ON_DISCONNECT_TITLE_STRING();
/** "Delete", action button for deleting something */
FOUNDATION_EXPORT NSString* DELETE_STRING();
/** "Delivered", Shows in the chat view when a message has been delivered */
FOUNDATION_EXPORT NSString* DELIVERED_STRING();
/** "Did you know you can now help fund future development directly within the app?", prompt users to donate money */
FOUNDATION_EXPORT NSString* DID_YOU_KNOW_DONATION_STRING();
/** "Your donation will help fund the continued development of ChatSecure.", Message shown when about to donate */
FOUNDATION_EXPORT NSString* DONATE_MESSAGE_STRING();
/** "Donate", Title for donation link */
FOUNDATION_EXPORT NSString* DONATE_STRING();
/** "Done", Title for button to press when user is finished */
FOUNDATION_EXPORT NSString* DONE_STRING();
/** "Download", Title for button to download something */
FOUNDATION_EXPORT NSString* DOWNLOAD_STRING();
/** "Do Not Disturb", Default message when a user status is set to do not disturb */
FOUNDATION_EXPORT NSString* DO_NOT_DISTURB_STRING();
/** "Database Error",  */
FOUNDATION_EXPORT NSString* Database_Error_String();
/** "Edit Account", Button to edit account details */
FOUNDATION_EXPORT NSString* EDIT_ACCOUNT_STRING();
/** "Email", The string describing account name or email address for a buddy */
FOUNDATION_EXPORT NSString* EMAIL_STRING();
/** "Beware! These logs are for debugging purposes only and will contain sensitive material like usernames, passwords, contacts, and message history. Disabling this option will delete all existing logs.", extra information about debug logging */
FOUNDATION_EXPORT NSString* ENABLE_DEBUG_LOGGING_HELP_STRING();
/** "Enable Debug Logging", switch label for toggling debug logs */
FOUNDATION_EXPORT NSString* ENABLE_DEBUG_LOGGING_STRING();
/** "Enable Push in Settings", button for enabling push messages in iOS system settings */
FOUNDATION_EXPORT NSString* ENABLE_PUSH_IN_SETTINGS_STRING();
/** "Enable Push", button for enabling push messages */
FOUNDATION_EXPORT NSString* ENABLE_PUSH_STRING();
/** "Encryption Error", Generic title for encryption errors */
FOUNDATION_EXPORT NSString* ENCRYPTION_ERROR_STRING();
/** "Enter a group name", The placeholder text for the text field to enter a group chat name or label */
FOUNDATION_EXPORT NSString* ENTER_GROUP_NAME_STRING();
/** "Error Creating Account", title label for error when creating account */
FOUNDATION_EXPORT NSString* ERROR_CREATING_ACCOUNT_STRING();
/** "Error", Title of error message pop-up box */
FOUNDATION_EXPORT NSString* ERROR_STRING();
/** "Experimental", Section for experimental settings */
FOUNDATION_EXPORT NSString* EXPERIMENTAL_STRING();
/** "Extended Away", Default message when a user status is set to extended away */
FOUNDATION_EXPORT NSString* EXTENDED_AWAY_STRING();
/** "Enable", enable permission */
FOUNDATION_EXPORT NSString* Enable_String();
/** "Enable Tor",  */
FOUNDATION_EXPORT NSString* Enable_Tor_String();
/** "Facebook", the name for facebook */
FOUNDATION_EXPORT NSString* FACEBOOK_STRING();
/** "File exceeds maximum size.", Error string for when file is too big. */
FOUNDATION_EXPORT NSString* FILE_EXCEEDS_MAX_SIZE_STRING();
/** "File Message", Text for file message summary */
FOUNDATION_EXPORT NSString* FILE_MESSAGE_STRING();
/** "File not found.", Error */
FOUNDATION_EXPORT NSString* FILE_NOT_FOUND_STRING();
/** "Fix Background Fetch...", prompt to fix background fetch */
FOUNDATION_EXPORT NSString* FIX_BACKGROUND_FETCH_STRING();
/** "Fix Permissions...", prompt to fix permissions */
FOUNDATION_EXPORT NSString* FIX_PERMISSIONS_STRING();
/** "Because the database contents is encrypted with your passphrase, you've lost access to your data and will need to delete and reinstall ChatSecure to continue. Password managers like 1Password or MiniKeePass can be helpful for generating and storing strong passwords.", Text describing what happens when the user has forgotten the passphrase */
FOUNDATION_EXPORT NSString* FORGOT_PASSPHRASE_INFO_STRING();
/** "Forgot Passphrase?", Label for button when you've forgotten the passphrase */
FOUNDATION_EXPORT NSString* FORGOT_PASSPHRASE_STRING();
/** "GitHub", Name of popular web based hosting service */
FOUNDATION_EXPORT NSString* GITHUB_STRING();
/** "Google Talk", the name for Google talk */
FOUNDATION_EXPORT NSString* GOOGLE_TALK_STRING();
/** "Group Chat", a subtitle label for a group chat */
FOUNDATION_EXPORT NSString* GROUP_CHAT_STRING();
/** "Make Admin", Label for granting admin privileges to someone in a group */
FOUNDATION_EXPORT NSString* GROUP_GRANT_ADMIN_STRING();
/** "you", This will be shown after your own JID in the group profile view */
FOUNDATION_EXPORT NSString* GROUP_INFO_YOU();
/** "Group Name", The title for the view to enter a group chat name or label */
FOUNDATION_EXPORT NSString* GROUP_NAME_STRING();
/** "Kick Out", Label for revoking membership for someone in a group */
FOUNDATION_EXPORT NSString* GROUP_REVOKE_MEMBERSHIP_STRING();
/** "Generate Secure Password", whether or not we should generate a strong password for them */
FOUNDATION_EXPORT NSString* Generate_Secure_Password();
/** "We can automatically generate you a secure password. If you choose your own, make sure it's a unique password you don't use anywhere else.", help text for password generator */
FOUNDATION_EXPORT NSString* Generate_Secure_Password_Hint();
/** "Help Translate", Label for button to open link to translate app */
FOUNDATION_EXPORT NSString* HELP_TRANSLATE_STRING();
/** "Hold to talk", Label for button to hold to record audio */
FOUNDATION_EXPORT NSString* HOLD_TO_TALK_STRING();
/** "Hostname", Label text for hostname field on login scree */
FOUNDATION_EXPORT NSString* HOSTNAME_STRING();
/** "Inbox", segmented control value for active conversations */
FOUNDATION_EXPORT NSString* INBOX_STRING();
/** "Incoming", Label for incoming data transfers */
FOUNDATION_EXPORT NSString* INCOMING_STRING();
/** "Info", Short for information, button title to get more information */
FOUNDATION_EXPORT NSString* INFO_STRING();
/** "Please choose a valid email address", detail title label for invalid email */
FOUNDATION_EXPORT NSString* INVALID_EMAIL_DETAIL_STRING();
/** "Invalid Email", title label for invalid email */
FOUNDATION_EXPORT NSString* INVALID_EMAIL_TITLE_STRING();
/** "Invite Friends", Button to invite friends */
FOUNDATION_EXPORT NSString* INVITE_FRIENDS_STRING();
/** "Share Invite", Label for inviting friends via URL */
FOUNDATION_EXPORT NSString* INVITE_LINK_STRING();
/** "The XMPP server does not support in-band registration", Error message for when in band registration is not supported */
FOUNDATION_EXPORT NSString* IN_BAND_ERROR_STRING();
/** "Jabber (XMPP)", the name for jabber, also include (XMPP) at the end */
FOUNDATION_EXPORT NSString* JABBER_STRING();
/** "Join Group", Text for joining existing XMPP room */
FOUNDATION_EXPORT NSString* JOIN_GROUP_STRING();
/** "Knock Sent", Text for label after knock is sent. Like knocking on a door */
FOUNDATION_EXPORT NSString* KNOCK_SENT_STRING();
/** "Knock", Label for button after to send push notification knock. Like knocking on a door */
FOUNDATION_EXPORT NSString* KNOCK_STRING();
/** "Language", string to bring up language selector */
FOUNDATION_EXPORT NSString* LANGUAGE_STRING();
/** "Login Automatically", Label for account setting that autologins on launch */
FOUNDATION_EXPORT NSString* LOGIN_AUTOMATICALLY_STRING();
/** "Log In", log in to account */
FOUNDATION_EXPORT NSString* LOGIN_STRING();
/** "Log Out", log out from account */
FOUNDATION_EXPORT NSString* LOGOUT_STRING();
/** "Manage ChatSecure Push account", Title for button to manage ChatSecure Push account */
FOUNDATION_EXPORT NSString* MANAGE_CHATSECURE_PUSH_ACCOUNT_STRING();
/** "Manage Debug Logs", Manage the device logs */
FOUNDATION_EXPORT NSString* MANAGE_DEBUG_LOGS_STRING();
/** "Manage My Keys", Button to manage your OTR and OMEMO keys */
FOUNDATION_EXPORT NSString* MANAGE_MY_KEYS();
/** "Maybe Later", button to do something later */
FOUNDATION_EXPORT NSString* MAYBE_LATER_STRING();
/** "The message could not be sent because this contact cannot receive your messages at this time. This could occur because they are offline, or if you are not authorized to send them messages.", Explanation for why a message could not be sent. */
FOUNDATION_EXPORT NSString* MESSAGE_COULD_NOT_BE_SENT_STRING();
/** "Notify Contacts of New Account", Title for toggle switch to spam your friends with your new account info */
FOUNDATION_EXPORT NSString* MESSAGE_FRIENDS_WITH_NEW_INFO_STRING();
/** "Ignore", Button to ignore the migrated buddy warning */
FOUNDATION_EXPORT NSString* MIGRATED_BUDDY_IGNORE();
/** "Your buddy has a different forwarding address than the jid you are currently chatting with. Do you want to switch to this account instead?", Explanation that buddy has a different prefered jid in the vcard */
FOUNDATION_EXPORT NSString* MIGRATED_BUDDY_INFO_STRING();
/** "Buddy has moved!", Title for migrated buddy header view */
FOUNDATION_EXPORT NSString* MIGRATED_BUDDY_STRING();
/** "Switch", Button to switch the chat over to the migrated account */
FOUNDATION_EXPORT NSString* MIGRATED_BUDDY_SWITCH();
/** "Migrate Account", Title for button to start migration tool */
FOUNDATION_EXPORT NSString* MIGRATE_ACCOUNT_STRING();
/** "We will automatically migrate your contacts from your old account to the new one, and archive your old conversations.\n\nIf you'd like, we can also notify your existing contacts that your account has moved.", Description detail text for account migration form */
FOUNDATION_EXPORT NSString* MIGRATION_FORM_DETAIL_STRING();
/** "Your account currently lives on the %1$@ servers. That chat service is no longer in service, so we're going to help move your account to a new server.", Explanation for why migration is needed */
FOUNDATION_EXPORT NSString* MIGRATION_INFO_STRING();
/** "Your account currently lives on the %1$@ servers. That chat service is closing on %2$@, so we're going to help move your account to a new server.", Explanation for why migration is needed, contains a shutdown date */
FOUNDATION_EXPORT NSString* MIGRATION_INFO_WITH_DATE_STRING();
/** "Your account has expired.", Explanation that your account has expired and you need to migrate */
FOUNDATION_EXPORT NSString* MIGRATION_NOTIFICATION_STRING();
/** "Your account is expiring in '%1$d' days.", Explanation that your account has expired and you need to migrate, contains a shutdown date */
FOUNDATION_EXPORT NSString* MIGRATION_NOTIFICATION_WITH_DATE_STRING();
/** "Get Started", Title for button to start migration tool */
FOUNDATION_EXPORT NSString* MIGRATION_START_STRING();
/** "It's time to move!", Title for migration header view */
FOUNDATION_EXPORT NSString* MIGRATION_STRING();
/** "More Ways to Help", button for additional ways to help support development of the app */
FOUNDATION_EXPORT NSString* MORE_WAYS_TO_HELP_STRING();
/** "My new account information", label for new account info for migration */
FOUNDATION_EXPORT NSString* MY_NEW_ACCOUNT_INFO_STRING();
/** "My QR Code", Your QR code */
FOUNDATION_EXPORT NSString* MY_QR_CODE();
/** "Me",  */
FOUNDATION_EXPORT NSString* Me_String();
/** "Microphone Disabled", microphone permission is disabled */
FOUNDATION_EXPORT NSString* Microphone_Disabled();
/** "To use this feature you must re-enable microphone permissions.", microphone permission is disabled */
FOUNDATION_EXPORT NSString* Microphone_Reenable_Please();
/** "Name", The string describing a buddy's display name */
FOUNDATION_EXPORT NSString* NAME_STRING();
/** "New Account", Title for New Account View */
FOUNDATION_EXPORT NSString* NEW_ACCOUNT_STRING();
/** "New SSL Certificate", Title for alert when a new SSL certificate is encountered */
FOUNDATION_EXPORT NSString* NEW_CERTIFICATE_STRING();
/** "New Message!", when a new message notification is received */
FOUNDATION_EXPORT NSString* NEW_MESSAGE_STRING();
/** "New", For a new settings value */
FOUNDATION_EXPORT NSString* NEW_STRING();
/** "Next", Label for button to go to next step */
FOUNDATION_EXPORT NSString* NEXT_STRING();
/** "Notifications", Label for notifications switch */
FOUNDATION_EXPORT NSString* NOTIFICATIONS_STRING();
/** "We could not find any trusted devices for this account.", Error message for not finding any devices */
FOUNDATION_EXPORT NSString* NO_DEVICES_ACCOUNT_ERROR_STRING();
/** "We could not find any trusted devices for this contact.", Error message for not finding any devices */
FOUNDATION_EXPORT NSString* NO_DEVICES_BUDDY_ERROR_STRING();
/** "No HTTP upload servers found.", Error string for when there are no XEP-0363 upload servers. */
FOUNDATION_EXPORT NSString* NO_HTTP_UPLOAD_SERVERS_STRING();
/** "Nickname", for choosing your XMPP vCard display name */
FOUNDATION_EXPORT NSString* Nickname_String();
/** "Offline", Label in buddy list for users that are offline */
FOUNDATION_EXPORT NSString* OFFLINE_STRING();
/** "OK", Accept the dialog */
FOUNDATION_EXPORT NSString* OK_STRING();
/** "Old", For an old settings value */
FOUNDATION_EXPORT NSString* OLD_STRING();
/** "Note: this does not automatically enable group encryption. It must also be manually enabled on a per-group basis.", toggling switch detail for showing OMEMO group encryption */
FOUNDATION_EXPORT NSString* OMEMO_GROUP_ENCRYPTION_DETAIL_STRING();
/** "OMEMO Group Encryption", For an old settings value */
FOUNDATION_EXPORT NSString* OMEMO_GROUP_ENCRYPTION_STRING();
/** "You're ready to use", String used when onboarding works */
FOUNDATION_EXPORT NSString* ONBOARDING_SUCCESS_STRING();
/** "Open in Chrome", Label to open link in the chrome web browser */
FOUNDATION_EXPORT NSString* OPEN_IN_CHROME();
/** "Open in Facebook", Label for button to open link in facebook app */
FOUNDATION_EXPORT NSString* OPEN_IN_FACEBOOK_STRING();
/** "Open in Safari", Label to open link in the Safari web browser */
FOUNDATION_EXPORT NSString* OPEN_IN_SAFARI();
/** "Open in Twitter", Label for button to open link in twitter app */
FOUNDATION_EXPORT NSString* OPEN_IN_TWITTER_STRING();
/** "Optional", Hint text for domain field telling user this field is not required */
FOUNDATION_EXPORT NSString* OPTIONAL_STRING();
/** "Other", Title for other miscellaneous settings group */
FOUNDATION_EXPORT NSString* OTHER_STRING();
/** "Message has not been sent because our buddy has ended the private conversation. We should either close the connection, or refresh it.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_CONNECTION_ENDED_STRING();
/** "An error occured while encrypting a message and the message was not sent.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_ENCRYPTION_ERROR_STRING();
/** "Our policy requires encryption but we are trying to send an unencrypted message out.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_ENCRYPTION_REQUIRED_STRING();
/** "Received a heartbeat.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_LOG_HEARTBEAT_RCVD_STRING();
/** "Sent a heartbeat.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_LOG_HEARTBEAT_SENT_STRING();
/** "Received our own OTR messages.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_MSG_REFLECTED_STRING();
/** "The previous message was resent.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_MSG_RESENT_STRING();
/** "Received and discarded a message intended for another instance.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_RCVDMSG_FOR_OTHER_INSTANCE_STRING();
/** "Received a general OTR error.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_RCVDMSG_GENERAL_ERR_STRING();
/** "The message received contains malformed data.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_RCVDMSG_MALFORMED_STRING();
/** "Received an encrypted message but cannot read it because no private connection is established yet.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_RCVDMSG_NOT_IN_PRIVATE_STRING();
/** "Received an unencrypted message.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_RCVDMSG_UNENCRYPTED_STRING();
/** "Cannot read the received message.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_RCVDMSG_UNREADABLE_STRING();
/** "Cannot recognize the type of OTR message received.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_RCVDMSG_UNRECOGNIZED_STRING();
/** "A private conversation could not be set up.", Error string for OTR message string */
FOUNDATION_EXPORT NSString* OTRL_MSGEVENT_SETUP_ERROR_STRING();
/** "Password", Label text for password field on login screen */
FOUNDATION_EXPORT NSString* PASSWORD_STRING();
/** "This device doesn't seem to be configured to make payments.", Error message when trying to make a purchase but payments haven't been set up yet */
FOUNDATION_EXPORT NSString* PAYMENTS_SETUP_ERROR_STRING();
/** "Payments Unavailable", Title for alert when user isn't allowed to make payments */
FOUNDATION_EXPORT NSString* PAYMENTS_UNAVAILABLE_STRING();
/** "Pending Approval", String for XMPP buddies when adding buddy is pending */
FOUNDATION_EXPORT NSString* PENDING_APPROVAL_STRING();
/** "Photo Library", Label for button to open up photo library and choose photo */
FOUNDATION_EXPORT NSString* PHOTO_LIBRARY_STRING();
/** "Picture Message", Text for media message summary */
FOUNDATION_EXPORT NSString* PICTURE_MESSAGE_STRING();
/** "Manage saved SSL certificates", subtitle for the certificate pinned setting */
FOUNDATION_EXPORT NSString* PINNED_CERTIFICATES_DESCRIPTION_STRING();
/** "Pinned Certificates", Button Lable to show all pinned SSL certificates */
FOUNDATION_EXPORT NSString* PINNED_CERTIFICATES_STRING();
/** "Please contact your server administrator.", Error string for when there is a server configuration error. */
FOUNDATION_EXPORT NSString* PLEASE_CONTACT_SERVER_OP_STRING();
/** "Port", Label for port number field for connecting to service */
FOUNDATION_EXPORT NSString* PORT_STRING();
/** "Could not retrieve public key from certificate", Error message when cannot get public key from SSL certificate */
FOUNDATION_EXPORT NSString* PUBLIC_KEY_ERROR_STRING();
/** "Push", Title for push-messaging related settings */
FOUNDATION_EXPORT NSString* PUSH_TITLE_STRING();
/** "Push Warning", Button title to show more information about Push messaging might not be working */
FOUNDATION_EXPORT NSString* PUSH_WARNING_STRING();
/** "Plaintext Only",  */
FOUNDATION_EXPORT NSString* Plaintext_Only();
/** "Plaintext (Opportunistic OTR)",  */
FOUNDATION_EXPORT NSString* Plaintext_Opportunistic_OTR();
/** "Profile", title for contacts profile view */
FOUNDATION_EXPORT NSString* Profile_String();
/** "QR code", Label for qr code image */
FOUNDATION_EXPORT NSString* QR_CODE_STRING();
/** "Recent", Title for header of Buddy list view with Recent Buddies */
FOUNDATION_EXPORT NSString* RECENT_STRING();
/** "Reject", Button title to reject a request such as a buddy request */
FOUNDATION_EXPORT NSString* REJECT_STRING();
/** "Release to delete", Label for instruction to delete current recording */
FOUNDATION_EXPORT NSString* RELEASE_TO_DELETE_STRING();
/** "Release to send", Label for instruction to send current audio */
FOUNDATION_EXPORT NSString* RELEASE_TO_SEND_STRING();
/** "Your password will be stored in the iOS Keychain of this device only, and is only as safe as your device passphrase or pin. However, it will not persist during a device backup/restore via iTunes, so please don't forget it, or you may lose your conversation history.", Text that describes what remembering your passphrase does */
FOUNDATION_EXPORT NSString* REMEMBER_PASSPHRASE_INFO_STRING();
/** "Remember Passphrase", Label for switch to save passphrase */
FOUNDATION_EXPORT NSString* REMEMBER_PASSPHRASE_STRING();
/** "Remember password", label for switch for whether or not we should save their password between launches */
FOUNDATION_EXPORT NSString* REMEMBER_PASSWORD_STRING();
/** "Remove", The String for a button to remove a buddy from the buddy list */
FOUNDATION_EXPORT NSString* REMOVE_STRING();
/** "Reply", Reply to an incoming message */
FOUNDATION_EXPORT NSString* REPLY_STRING();
/** "Required", String to let user know a certain field like a password is required to create an account */
FOUNDATION_EXPORT NSString* REQUIRED_STRING();
/** "Resending this message will use %@.", Describe what resending will do the %@ will be replaced withe the method OTR/OMEMO/Plaintext */
FOUNDATION_EXPORT NSString* RESEND_DESCRIPTION_STRING();
/** "Resend Message", Ttitle for alert view to resend a message */
FOUNDATION_EXPORT NSString* RESEND_MESSAGE_TITLE();
/** "Resend", Label for button to resend message. */
FOUNDATION_EXPORT NSString* RESEND_STRING();
/** "Reset", e.g. for resetting push account */
FOUNDATION_EXPORT NSString* RESET_STRING();
/** "Resource", Label for text input for XMPP resource */
FOUNDATION_EXPORT NSString* RESOURCE_STRING();
/** "Removed By Server",  */
FOUNDATION_EXPORT NSString* Removed_By_Server();
/** "Saved Certificates", Title for listing the user saved SSL certificates */
FOUNDATION_EXPORT NSString* SAVED_CERTIFICATES_STRING();
/** "Save", Title for button for saving a setting */
FOUNDATION_EXPORT NSString* SAVE_STRING();
/** "Scan QR", Label for sharing via QR Code */
FOUNDATION_EXPORT NSString* SCAN_QR_STRING();
/** "Search", Label for text field where you search for a buddy */
FOUNDATION_EXPORT NSString* SEARCH_STRING();
/** "Security", Title heading in settings */
FOUNDATION_EXPORT NSString* SECURITY_STRING();
/** "Security Warning", Title of alert box warning about security issues */
FOUNDATION_EXPORT NSString* SECURITY_WARNING_STRING();
/** "Sending", Label text for when a transfer is in progress (normally followed by a percent value 34%) */
FOUNDATION_EXPORT NSString* SENDING_STRING();
/** "Send %@ encrypted message", The placeholder text in the chat view where the message should go */
FOUNDATION_EXPORT NSString* SEND_ENCRYPTED_STRING();
/** "Send Feedback", String on button to email feedback */
FOUNDATION_EXPORT NSString* SEND_FEEDBACK_STRING();
/** "Send plaintext message", The placeholder text in the chat view where the message should go */
FOUNDATION_EXPORT NSString* SEND_PLAINTEXT_STRING();
/** "Server Information", button to show more information about your XMPP server */
FOUNDATION_EXPORT NSString* SERVER_INFORMATION_STRING();
/** "Settings", Title for the Settings screen */
FOUNDATION_EXPORT NSString* SETTINGS_STRING();
/** "Chat with me securely", Body of SMS or email when sharing a link to the app */
FOUNDATION_EXPORT NSString* SHARE_MESSAGE_STRING();
/** "Share", Title for sharing a link to the app */
FOUNDATION_EXPORT NSString* SHARE_STRING();
/** "Show Console", button label for showing log console */
FOUNDATION_EXPORT NSString* SHOW_CONSOLE_STRING();
/** "Would you like to connect to UserVoice to send feedback?", actionsheet for showing uservoice feedback service */
FOUNDATION_EXPORT NSString* SHOW_USERVOICE_STRING();
/** "Sign Up", title label for signing up for a new account */
FOUNDATION_EXPORT NSString* SIGN_UP_STRING();
/** "Skip", Label for button to skip this step */
FOUNDATION_EXPORT NSString* SKIP_STRING();
/** "Someone is typing...", received a typing notification */
FOUNDATION_EXPORT NSString* SOMEONE_IS_TYPING_STRING();
/** "Someone", A placeholder for a buddy's username like Someone wants to chat. */
FOUNDATION_EXPORT NSString* SOMEONE_STRING();
/** "Check out the source here on Github", let users know source is on Github */
FOUNDATION_EXPORT NSString* SOURCE_STRING();
/** "Server", server selection section title */
FOUNDATION_EXPORT NSString* Server_String();
/** "Choose from a selection of public servers, or use your own.", server selection footer */
FOUNDATION_EXPORT NSString* Server_String_Hint();
/** "Show Advanced Encryption Settings",  */
FOUNDATION_EXPORT NSString* Show_Advanced_Encryption_Settings();
/** "Show Advanced Options", toggle switch for show advanced */
FOUNDATION_EXPORT NSString* Show_Advanced_Options();
/** "Thank you for your contribution!", string shown if user has already paid */
FOUNDATION_EXPORT NSString* THANK_YOU_FOR_CONTRIBUTION();
/** "Tor is an experimental feature, please use with caution.", Message for warning about using tor network */
FOUNDATION_EXPORT NSString* TOR_WARNING_MESSAGE_STRING();
/** "Twitter", Name of the popular social tweeting site */
FOUNDATION_EXPORT NSString* TWITTER_STRING();
/** "Unable to Send Message", Title for error message */
FOUNDATION_EXPORT NSString* UNABLE_TO_SEND_STRING();
/** "Unarchive", Verb. action for moving archived converation back to inbox */
FOUNDATION_EXPORT NSString* UNARCHIVE_ACTION_STRING();
/** "plaintext", Label for messages that are not encrypted */
FOUNDATION_EXPORT NSString* UNENCRYPTED_STRING();
/** "Unknown Error", Describes an error without a known cause */
FOUNDATION_EXPORT NSString* UNKNOWN_ERROR_STRING();
/** "Unlock", Label for button to unlock app */
FOUNDATION_EXPORT NSString* UNLOCK_STRING();
/** "This message was received from an untrusted device.", Error message description */
FOUNDATION_EXPORT NSString* UNTRUSTED_DEVICE_REVEIVED_STRING();
/** "This message was sent to an untrusted device.", Error message description */
FOUNDATION_EXPORT NSString* UNTRUSTED_DEVICE_SENT_STRING();
/** "Untrusted Device", Title for error message */
FOUNDATION_EXPORT NSString* UNTRUSTED_DEVICE_STRING();
/** "Username", Label text for username field on login screen */
FOUNDATION_EXPORT NSString* USERNAME_STRING();
/** "Canceled", Describes a state entered by user cancelation */
FOUNDATION_EXPORT NSString* USER_CANCELED_STRING();
/** "Camera", Label for button to take a photo from camera */
FOUNDATION_EXPORT NSString* USE_CAMERA_STRING();
/** "Unrecognized Invite Format", shown when invite QR code doesnt work */
FOUNDATION_EXPORT NSString* Unrecognized_Invite_Format();
/** "Valid certificate", shown to show that the certificate was valid to the system */
FOUNDATION_EXPORT NSString* VALID_CERTIFICATE_STRING();
/** "Verified", To let the user know the fingerprint as been checked */
FOUNDATION_EXPORT NSString* VERIFIED_STRING();
/** "Verify Fingerprint", Title of the dialog for fingerprint verification */
FOUNDATION_EXPORT NSString* VERIFY_FINGERPRINT_STRING();
/** "Verify", Shown when verifying fingerprints */
FOUNDATION_EXPORT NSString* VERIFY_STRING();
/** "Version", when displaying version numbers such as 1.0.0 */
FOUNDATION_EXPORT NSString* VERSION_STRING();
/** "Video Message", Text for media message summary */
FOUNDATION_EXPORT NSString* VIDEO_MESSAGE_STRING();
/** "View profile to review contact's devices or change encryption settings.", Describe how to change a contact's device settings */
FOUNDATION_EXPORT NSString* VIEW_PROFILE_DESCRIPTION_STRING();
/** "View Profile", The label for a button to view the buddy profile */
FOUNDATION_EXPORT NSString* VIEW_PROFILE_STRING();
/** "Waiting", Label text for when a transfer has not started yet */
FOUNDATION_EXPORT NSString* WAITING_STRING();
/** "wants to chat.", This string follows a user's dislplay name or username ex Bob wants to chat. */
FOUNDATION_EXPORT NSString* WANTS_TO_CHAT_STRING();
/** "Failed to connect to XMPP server. Please check your login credentials and internet connection and try again.", Message when cannot connect to XMPP server */
FOUNDATION_EXPORT NSString* XMPP_FAIL_STRING();
/** "XMPP + Tor", Title for xmpp accounts that connect through the Tor network */
FOUNDATION_EXPORT NSString* XMPP_TOR_STRING();
/** "user@example.com", Example of a username using the words user and example */
FOUNDATION_EXPORT NSString* XMPP_USERNAME_EXAMPLE_STRING();
/** "You have been invited to the ´%@´ group.", Title of screen for joining/not joining group */
FOUNDATION_EXPORT NSString* YOU_HAVE_BEEN_INVITED_TO_GROUP_STRING();
/** "Bad certificate format", SSL error message */
FOUNDATION_EXPORT NSString* errSSLBadCertString();
/** "Bad SSLCipherSuite", SSL error message */
FOUNDATION_EXPORT NSString* errSSLBadCipherSuiteString();
/** "Configuration error", SSL error message */
FOUNDATION_EXPORT NSString* errSSLBadConfigurationString();
/** "Bad MAC", SSL error message */
FOUNDATION_EXPORT NSString* errSSLBadRecordMacString();
/** "Insufficient buffer provided", SSL error message */
FOUNDATION_EXPORT NSString* errSSLBufferOverflowString();
/** "Chain had an expired cert", SSL error message */
FOUNDATION_EXPORT NSString* errSSLCertExpiredString();
/** "Chain had a cert not yet valid", SSL error message */
FOUNDATION_EXPORT NSString* errSSLCertNotYetValidString();
/** "Server has requested a client cert", SSL error message */
FOUNDATION_EXPORT NSString* errSSLClientCertRequestedString();
/** "Connection closed via error", SSL error message */
FOUNDATION_EXPORT NSString* errSSLClosedAbortString();
/** "Connection closed gracefully", SSL error message */
FOUNDATION_EXPORT NSString* errSSLClosedGracefulString();
/** "Server closed session with no notification", SSL error message */
FOUNDATION_EXPORT NSString* errSSLClosedNoNotifyString();
/** "Peer dropped connection before responding", SSL error message */
FOUNDATION_EXPORT NSString* errSSLConnectionRefusedString();
/** "Underlying cryptographic error", SSL error message */
FOUNDATION_EXPORT NSString* errSSLCryptoString();
/** "Decryption failure", SSL error message */
FOUNDATION_EXPORT NSString* errSSLDecryptionFailString();
/** "Fatal alert", SSL error message */
FOUNDATION_EXPORT NSString* errSSLFatalAlertString();
/** "Peer host name mismatch", SSL error message */
FOUNDATION_EXPORT NSString* errSSLHostNameMismatchString();
/** "Illegal parameter", SSL error message */
FOUNDATION_EXPORT NSString* errSSLIllegalParamString();
/** "Internal error", SSL error message */
FOUNDATION_EXPORT NSString* errSSLInternalString();
/** "Module attach failure", SSL error message */
FOUNDATION_EXPORT NSString* errSSLModuleAttachString();
/** "Cipher Suite negotiation failure", SSL error message */
FOUNDATION_EXPORT NSString* errSSLNegotiationString();
/** "Cert chain not verified by root", SSL error message */
FOUNDATION_EXPORT NSString* errSSLNoRootCertString();
/** "Access denied", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerAccessDeniedString();
/** "Peer cert is valid, or was ignored if verification disabled", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerAuthCompletedString();
/** "Miscellaneous bad certificate", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerBadCertString();
/** "Bad MAC", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerBadRecordMacString();
/** "Certificate expired", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerCertExpiredString();
/** "Certificate revoked", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerCertRevokedString();
/** "Unknown certificate", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerCertUnknownString();
/** "Decoding error", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerDecodeErrorString();
/** "Decompression failure", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerDecompressFailString();
/** "Decryption error", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerDecryptErrorString();
/** "Decryption failed", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerDecryptionFailString();
/** "Export restriction", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerExportRestrictionString();
/** "Handshake failure", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerHandshakeFailString();
/** "Insufficient security", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerInsufficientSecurityString();
/** "Internal error", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerInternalErrorString();
/** "No renegotiation allowed", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerNoRenegotiationString();
/** "Bad protocol version", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerProtocolVersionString();
/** "Record overflow", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerRecordOverflowString();
/** "Unexpected message received", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerUnexpectedMsgString();
/** "Unknown Cert Authority", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerUnknownCAString();
/** "Bad unsupported cert format", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerUnsupportedCertString();
/** "User canceled", SSL error message */
FOUNDATION_EXPORT NSString* errSSLPeerUserCancelledString();
/** "SSL protocol error", SSL error message */
FOUNDATION_EXPORT NSString* errSSLProtocolString();
/** "Record overflow", SSL error message */
FOUNDATION_EXPORT NSString* errSSLRecordOverflowString();
/** "Attempt to restore an unknown session", SSL error message */
FOUNDATION_EXPORT NSString* errSSLSessionNotFoundString();
/** "Unexpected (skipped) record in DTLS", SSL error message */
FOUNDATION_EXPORT NSString* errSSLUnexpectedRecordString();
/** "Valid cert chain, untrusted root", SSL error message */
FOUNDATION_EXPORT NSString* errSSLUnknownRootCertString();
/** "I/O would block (not fatal)", SSL error message */
FOUNDATION_EXPORT NSString* errSSLWouldBlockString();
/** "Invalid certificate chain", SSL error message */
FOUNDATION_EXPORT NSString* errSSLXCertChainInvalidString();
/** "No Error", SSL error message */
FOUNDATION_EXPORT NSString* noErrString();
/** "Default", default string to revert to normal language behaviour */
FOUNDATION_EXPORT NSString* DEFAULT_LANGUAGE_STRING();
NS_ASSUME_NONNULL_END
