# Uncomment the lines below you want to change by removing the # in the beginning

workspace "../ChatSecure.xcworkspace"

# A list of devices you want to take the screenshots from
devices([
  "iPad Pro (12.9 inch)"
])

#"iPhone 7 Plus"

languages([
  'en-US',
  'de-DE',
  'zh-Hans'
])

localize_simulator true

# The name of the scheme which contains the UI Tests
scheme "ChatSecureUITests"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
