###################### App Metadata ######################
# Update the app description and metadata in the ./metadata folder

# default_language "en"

###################### Screenshots ######################
# Store all screenshots in the ./screenshots folder separated
# by language. If you use snapshot, this happens automatically

###################### IPA File ######################
# This part is only relevant, if you want to submit a new binary
# If you don't use fastlane (https://github.com/KrauseFx/fastlane)
# you can set the path to your ipa file using:
# ipa "./app.ipa"

# to provide an ipa file for TestFlight distribution, use beta_ipa 
# beta_ipa "./app.ipa"

# The version of your app - remove this if you provide an ipa file
app_version "4.3.9"
submit_for_review false
skip_binary_upload true
# overwrite_screenshots true
skip_screenshots true
force true

metadata_path "./Submodules/ChatSecure-Metadata/metadata"
screenshots_path "./Submodules/ChatSecure-Metadata/screenshots"

release_notes({
  'default' => "v4.3.9:
* Fix issue where fingerprint trust settings cannot be saved

v4.3.8:
* Improved launch performance, reduced binary size and memory usage
* Tor 0.4.0.5
* SQLCipher 4.2.0
* Update 3rd party dependencies

Changelog: https://github.com/chatsecure/chatsecure-ios/compare/v4.3.8...v4.3.9
",
})

###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/KrauseFx/deliver/blob/master/Deliverfile.md

# skip_pdf true

###################### Automatically generated ######################
# Feel free to remove the following lines if you use fastlane

app_identifier "com.chrisballinger.ChatSecure" # The bundle identifier of your app
# apple_id "464200063" # This is NOT your Apple login ID, but the App ID of your app
