# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  # "iPhone 8",
  # "iPhone 8 Plus",
  # "iPhone SE",
  "iPhone Xs Max",
  # "iPhone X",
  # "iPad Pro (12.9-inch)",
  # "iPad Pro (9.7-inch)",
  "iPad Pro (12.9-inch) (3rd generation)",
])

# languages([
#   "it", #{}"nl-NL", "pt-BR", "pt-PT", "tr", 
# ])

# languages([
#   "da", "el", "es-ES", "it", "nl-NL", "pt-BR", "pt-PT", "tr", 
# ])

# languages([
#   "da", "de-DE", "el", "en-US", "es-ES", "fi", "fr-FR", "id", "it", "ja",
#   "nl-NL", "no", "pt-BR", "pt-PT", "ru", "sv", "tr", "vi", "zh-Hans", "zh-Hant"
# ])

localize_simulator true
skip_open_summary true

derived_data_path "./fastlane/DerivedData"

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")

# Where should the resulting screenshots be stored?
output_directory("./Submodules/ChatSecure-Metadata/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
