/*
 *  SNAC_Types.h
 *  TalkToOscar
 *
 *  Created by Alex Nichol on 3/23/11.
 *  Copyright 2011 __MyCompanyName__. All rights reserved.
 *
 */

#define SNAC_OSERVICE 1
#define OSERVICE__ERROR 1
#define OSERVICE__CLIENT_ONLINE 2
#define OSERVICE__HOST_ONLINE 3
#define OSERVICE__SERVICE_REQUEST 4
#define OSERVICE__SERVICE_RESPONSE 5
#define OSERVICE__RATE_PARAMS_QUERY 6
#define OSERVICE__RATE_PARAMS_REPLY 7
#define OSERVICE__RATE_ADD_PARAM_SUB 8
#define OSERVICE__RATE_PARAM_CHANGE 10
#define OSERVICE__NICK_INFO_QUERY 14
#define OSERVICE__NICK_INFO_UPDATE 15
#define OSERVICE__IDLE_NOTIFICATION 17
#define OSERVICE__SET_NICKINFO_FIELDS 30

#define SNAC_LOCATE 2
#define LOCATE__RIGHTS_QUERY 2
#define LOCATE__RIGHTS_REPLY 3
#define LOCATE__SET_INFO 4
#define LOCATE__USER_INFO_QUERY2 21
#define LOCATE__USER_INFO_REPLY 6

#define SNAC_BUDDY 3
#define BUDDY__RIGHTS_QUERY 2
#define BUDDY__RIGHTS_REPLY 3
#define BUDDY__REJECT_NOTIFICATION 10
#define BUDDY__ARRIVED 11
#define BUDDY__DEPARTED 12
#define BUDDY__ADD_TEMP_BUDDIES 15
#define BUDDY__DEL_TEMP_BUDDIES 16

#define SNAC_ICBM 4
#define ICBM__ERROR 1
#define ICBM__ADD_PARAMETERS 2
#define ICBM__PARAMETER_QUERY 4
#define ICBM__CHANNEL_MSG_TOHOST 6
#define ICBM__CHANNEL_MSG_TOCLIENT 7
#define ICBM__MISSED_CALLS 10
#define ICBM__CLIENT_ERR 11
#define ICBM__OFFLINE_RETRIEVE 16
#define ICBM__CLIENT_EVENT 20

#define SNAC_PD 9
#define PD__RIGHTS_QUERY 2
#define PD__RIGHTS_REPLY 3

#define SNAC_BART 16
#define BART__ERROR 1
#define BART__UPLOAD 2
#define BART__UPLOAD_REPLY 3
#define BART__DOWNLOAD2 6
#define BART__DOWNLOAD_REPLY2 7

#define SNAC_FEEDBAG 19
#define FEEDBAG__RIGHTS_QUERY 2
#define FEEDBAG__RIGHTS_REPLY 3
#define FEEDBAG__QUERY 4
#define FEEDBAG__REPLY 6
#define FEEDBAG__USE 7
#define FEEDBAG__INSERT_ITEMS 8
#define FEEDBAG__UPDATE_ITEMS 9
#define FEEDBAG__DELETE_ITEMS 10
#define FEEDBAG__STATUS 14
#define FEEDBAG__START_CLUSTER 17
#define FEEDBAG__END_CLUSTER 18
