NSLocalizedString( @"Buddy List",@"Title for the buddy list tab")
NSLocalizedString( @"Conversations",@"Title for the conversations tab")
NSLocalizedString( @"Accounts",@"Title for the accounts tab")
NSLocalizedString( @"About",@"Title for the about page")
NSLocalizedString( @"Chat",@"Title for chat view")
NSLocalizedString( @"Cancel",@"Cancel an alert window")
NSLocalizedString( @"Initiate Encrypted Chat",@"Shown when starting an encrypted chat session")
NSLocalizedString( @"Cancel Encrypted Chat",@"Shown when ending an encrypted chat session")
NSLocalizedString( @"Verify",@"Shown when verifying fingerprints")
NSLocalizedString( @"Verified",@"Shown when verifying fingerprints")
NSLocalizedString( @"Not Verified",@"Not Verfied or cancle verified")
NSLocalizedString( @"Verify Later",@"Shown when verifying fingerprings")
NSLocalizedString( @"Clear Chat History",@"String shown in dialog for removing chat history")
NSLocalizedString( @"Send",@"For sending a message")
NSLocalizedString( @"OK",@"Accept the dialog")
NSLocalizedString( @"Recent",@"Title for header of Buddy list view with Recent Buddies")
NSLocalizedString( @"Fingerprint for you",@"your fingerprint")
NSLocalizedString( @"Purported fingerprint for",@"the alleged fingerprint of their other person")
NSLocalizedString( @"You must be in a secure conversation first.",@"Inform user that they must be secure their conversation before doing that action")
NSLocalizedString( @"Verify Fingerprint",@"Title of the dialog for fingerprint verification")
NSLocalizedString( @"Log in on the Settings page (found on top right corner of buddy list) and then select a buddy from the Buddy List to start chatting.",@"Instructions on how to start using the program")
NSLocalizedString( @"Open in Safari",@"Shown when trying to open a link, asking if they want to switch to Safari to view it")
NSLocalizedString( @"Disconnected",@"Title of alert when user is disconnected from protocol")
NSLocalizedString( @"You (%@) have disconnected.",@"Message shown when user is disconnected")
NSLocalizedString( @"When you leave this conversation it will be deleted forever.",@"Warn user that conversation will be deleted after leaving it")
NSLocalizedString( @"Warning: This chat is not encrypted",@"Warn user that the current chat is not secure")
NSLocalizedString( @"The conversation with %@ is no longer secure.",@"Warn user that the current chat is no longer secure")
NSLocalizedString( @"This chat is secured",@"Warns user that the current chat is secure")
NSLocalizedString( @"This chat is secured and verified",@"Warns user that the current chat is secure and verified")
NSLocalizedString( @"Active",@"String to be displayed when a buddy is Active")
NSLocalizedString( @"Typing",@"String to be displayed when a buddy is currently composing a message")
NSLocalizedString( @"Entered Text",@"String to be displayed when a buddy has stopped composing and text has been entered")
NSLocalizedString( @"Inactive",@"String to be displayed when a budy has become inactive")
NSLocalizedString( @"Gone",@"String to be displayed when a buddy is inactive for an extended period of time")
NSLocalizedString( @"Ignore",@"Ignore an incoming message")
NSLocalizedString( @"Reply",@"Reply to an incoming message")
NSLocalizedString( @"Offline",@"Label in buddylist for users that are offline")
NSLocalizedString( @"Away",@"Label in buddylist for users that are away")
NSLocalizedString( @"Available",@"Label in buddylist for users that are available")
NSLocalizedString( @"is now offline",@"Message shown inline for users that are offline")
NSLocalizedString( @"is now away",@"Message shown inline for users that are away")
NSLocalizedString( @"is now available",@"Message shown inline for users that are available")
NSLocalizedString( @"Security Warning",@"Title of alert box warning about security issues")
NSLocalizedString( @"Agree",@"Agree to EULA")
NSLocalizedString( @"Disagree",@"Disagree with EULA")
NSLocalizedString( @"Error!",@"Title of error message popup box")
NSLocalizedString( @"Failed to start authenticating. Please try again.",@"Authentication failed, tell user to try again")
NSLocalizedString( @"Failed to connect to XMPP server. Please check your login credentials and internet connection and try again.",@"Message when cannot connect to XMPP server")
NSLocalizedString( @"Domain needs to be set manually when specifying a custom port",@"Message when port is changed but domain not set")
NSLocalizedString( @"Logging in...",@"shown during the login proceess")
NSLocalizedString( @"You must enter a username and a password to login.",@"error message shown when user doesnt fill in a username or password")
NSLocalizedString( @"Basic",@"string to describe basic set of settings")
NSLocalizedString( @"Advanced",@"stirng to describe advanced set of settings")
NSLocalizedString( @"SSL Hostname Mismatch",@"stirng for settings to allow ssl mismatch")
NSLocalizedString( @"Self Signed SSL",@"string for settings to allow self signed ssl stirng")
NSLocalizedString( @"Port",@"Label for port number field for connecting to service")
NSLocalizedString( @"user@gmail.com",@"example of a google talk account")
NSLocalizedString( @"Required",@"String to let user know a certain field like a password is required to create an account")
NSLocalizedString( @"Send Delivery Receipts",@"String in login settings asking to send delivery receipts")
NSLocalizedString( @"Send Typing Notificaction",@"Stirng in login settings asking to send typing notification")
NSLocalizedString( @"Log Out",@"log out from account")
NSLocalizedString( @"Log In",@"log in to account")
NSLocalizedString( @"Logout from OSCAR?",@"Ask user if they want to logout of OSCAR")
NSLocalizedString( @"Logout from XMPP?",@"ask user if they want to log out of xmpp")
NSLocalizedString( @"Delete Account?",@"Ask user if they want to delete the stored account information")
NSLocalizedString( @"Permanently delete",@"Ask user if they want to delete the stored account information")
NSLocalizedString( @"No Saved Accounts",@"Message infomring user that there are no accounts currently saved")
NSLocalizedString( @"ChatSecure is brought to you by many open source projects",@"for attribution of other projects")
NSLocalizedString( @"Check out the source here on Github",@"let users know source is on Github")
NSLocalizedString( @"Contribute a translation",@"label for a link to contribute a new translation")
NSLocalizedString( @"Project Homepage",@"label for link to ChatSecure project website")
NSLocalizedString( @"Version",@"when displaying version numbers such as 1.0.0")
NSLocalizedString( @"Username",@"Label text for username field on login screen")
NSLocalizedString( @"Password",@"Label text for password field on login screen")
NSLocalizedString( @"Domain",@"Label text for domain field on login scree")
NSLocalizedString( @"Login to",@"Label for button describing which protocol you're logging into, will be followed by a protocol such as XMPP or AIM during layout")
NSLocalizedString( @"Remember username",@"label for switch for whether or not we should save their username between launches")
NSLocalizedString( @"Remember password",@"label for switch for whether or not we should save their password between launches")
NSLocalizedString( @"Optional",@"Hint text for domain field telling user this field is not required")
NSLocalizedString( @"Your Facebook username is not the email address that you use to login to Facebook",@"Text that makes it clear which username to use")
NSLocalizedString( @"Send Crash Reports",@"Title for crash reports settings switch")
NSLocalizedString( @"Automatically send anonymous crash logs (opt-in)",@"Description for crash reports settings switch")
NSLocalizedString( @"Other",@"Title for other miscellaneous settings group")
NSLocalizedString( @"Self-Signed SSL",@"Title for settings cell on whether or not the XMPP library should allow self-signed SSL certificates")
NSLocalizedString( @"Hostname Mismatch",@"Title for settings cell on whether or not the XMPP library should allow SSL hostname mismatch")
NSLocalizedString( @"Warning: Use with caution! This may reduce your security.",@"Cell description text that warns users that enabling that option may reduce their security.")
NSLocalizedString( @"Auto-delete",@"Title for automatic conversation deletion setting")
NSLocalizedString( @"Delete chats on disconnect",@"Description for automatic conversation deletion")
NSLocalizedString( @"Font Size",@"Size for the font in the chat screen")
NSLocalizedString( @"Size for font in chat view",@"description for what the font size setting affects")
NSLocalizedString( @"Signout Warning",@"Title for setting about showing a warning before disconnection")
NSLocalizedString( @"1 Minute Alert Before Disconnection",@"Description for disconnection warning setting")
NSLocalizedString( @"Default",@"default string to revert to normal language behaviour")
NSLocalizedString( @"Settings",@"Title for the Settings screen")
NSLocalizedString( @"Share",@"Title for sharing a link to the app")
NSLocalizedString( @"Not Available",@"Shown when a feature is not available, for example SMS")
NSLocalizedString( @"Chat with me securely",@"Body of SMS or email when sharing a link to the app")
NSLocalizedString( @"Connected",@"Whether or not account is logged in")
NSLocalizedString( @"Send Feedback",@"String on button to email feedback")
NSLocalizedString( @"Language",@"string to bring up language selector")
NSLocalizedString( @"Language Change",@"Stirng of title to alert user langague is change")
NSLocalizedString( @"In order to change langugages return to the home screen and remove ChatSecure from the recently used apps",@"Message alerting user that they need to return to the home screen and force close ChatSecure")
NSLocalizedString( @"Save",@"Title for button for saving a setting")
NSLocalizedString( @"New",@"For a new settings value")
NSLocalizedString( @"Old",@"For an old settings value")
NSLocalizedString( @"Done",@"Title for button to press when user is finished")
NSLocalizedString( @"This QR Code contains a link to http://omniqrcode.com/q/chatsecure and will redirect to the App Store.",@"Instructions label text underneath QR code")
NSLocalizedString( @"Background session will expire in one minute.",@"Message displayed in Notification Manager when session will expire in one minute")
NSLocalizedString( @"Read",@"Title for action button on alert dialog, used as a verb in the present tense")
NSLocalizedString( @"New Account",@"Title for New Account View")
NSLocalizedString( @"OSCAR Instant Messenger",@"the name for AIM")
NSLocalizedString( @"Google Talk",@"the name for google talk")
NSLocalizedString( @"Facebook",@"the name for facebook")
NSLocalizedString( @"Jabber (XMPP)",@"the name for jabber, also include (XMPP) at the end")
NSLocalizedString( @"Allow Plaintext Authentication",@"Setting name for allowing authentication to happen in plain text or in the clear")
NSLocalizedString( @"Require TLS",@"Setting name for requiring a TLS connection")
