#define a1 NSLocalizedString(@"Buddy List" , @"Title for the buddy list tab")
#define a2 NSLocalizedString(@"Conversations" , @"Title for the conversations tab")
#define a3 NSLocalizedString(@"Accounts" , @"Title for the accounts tab")
#define a4 NSLocalizedString(@"About" , @"Title for the about page")
#define a5 NSLocalizedString(@"Chat" , @"Title for chat view")
#define a6 NSLocalizedString(@"Cancel" , @"Cancel an alert window")
#define a7 NSLocalizedString(@"Initiate Encrypted Chat" , @"Shown when starting an encrypted chat session")
#define a8 NSLocalizedString(@"Cancel Encrypted Chat" , @"Shown when ending an encrypted chat session")
#define a9 NSLocalizedString(@"Verify" , @"Shown when verifying fingerprints")
#define a10 NSLocalizedString(@"Verified" , @"Shown when verifying fingerprints")
#define a11 NSLocalizedString(@"Not Verified" , @"Not Verfied or cancle verified")
#define a12 NSLocalizedString(@"Verify Later" , @"Shown when verifying fingerprings")
#define a13 NSLocalizedString(@"Clear Chat History" , @"String shown in dialog for removing chat history")
#define a14 NSLocalizedString(@"Send" , @"For sending a message")
#define a15 NSLocalizedString(@"OK" , @"Accept the dialog")
#define a16 NSLocalizedString(@"Recent" , @"Title for header of Buddy list view with Recent Buddies")
#define a17 NSLocalizedString(@"Fingerprint for you" , @"your fingerprint")
#define a18 NSLocalizedString(@"Purported fingerprint for" , @"the alleged fingerprint of their other person")
#define a19 NSLocalizedString(@"You must be in a secure conversation first." , @"Inform user that they must be secure their conversation before doing that action")
#define a20 NSLocalizedString(@"Verify Fingerprint" , @"Title of the dialog for fingerprint verification")
#define a21 NSLocalizedString(@"Log in on the Settings page (found on top right corner of buddy list) and then select a buddy from the Buddy List to start chatting." , @"Instructions on how to start using the program")
#define a22 NSLocalizedString(@"Open in Safari" , @"Shown when trying to open a link, asking if they want to switch to Safari to view it")
#define a23 NSLocalizedString(@"Disconnected" , @"Title of alert when user is disconnected from protocol")
#define a24 NSLocalizedString(@"You (%@) have disconnected." , @"Message shown when user is disconnected")
#define a25 NSLocalizedString(@"When you leave this conversation it will be deleted forever." , @"Warn user that conversation will be deleted after leaving it")
#define a26 NSLocalizedString(@"Warning: This chat is not encrypted" , @"Warn user that the current chat is not secure")
#define a27 NSLocalizedString(@"The conversation with %@ is no longer secure." , @"Warn user that the current chat is no longer secure")
#define a28 NSLocalizedString(@"This chat is secured" , @"Warns user that the current chat is secure")
#define a29 NSLocalizedString(@"This chat is secured and verified" , @"Warns user that the current chat is secure and verified")
#define a30 NSLocalizedString(@"Active" , @"String to be displayed when a buddy is Active")
#define a31 NSLocalizedString(@"Typing" , @"String to be displayed when a buddy is currently composing a message")
#define a32 NSLocalizedString(@"Entered Text" , @"String to be displayed when a buddy has stopped composing and text has been entered")
#define a33 NSLocalizedString(@"Inactive" , @"String to be displayed when a budy has become inactive")
#define a34 NSLocalizedString(@"Gone" , @"String to be displayed when a buddy is inactive for an extended period of time")
#define a35 NSLocalizedString(@"Ignore" , @"Ignore an incoming message")
#define a36 NSLocalizedString(@"Reply" , @"Reply to an incoming message")
#define a37 NSLocalizedString(@"Offline" , @"Label in buddylist for users that are offline")
#define a38 NSLocalizedString(@"Away" , @"Label in buddylist for users that are away")
#define a39 NSLocalizedString(@"Available" , @"Label in buddylist for users that are available")
#define a40 NSLocalizedString(@"is now offline" , @"Message shown inline for users that are offline")
#define a41 NSLocalizedString(@"is now away" , @"Message shown inline for users that are away")
#define a42 NSLocalizedString(@"is now available" , @"Message shown inline for users that are available")
#define a43 NSLocalizedString(@"Security Warning" , @"Title of alert box warning about security issues")
#define a44 NSLocalizedString(@"Agree" , @"Agree to EULA")
#define a45 NSLocalizedString(@"Disagree" , @"Disagree with EULA")
#define a46 NSLocalizedString(@"Error!" , @"Title of error message popup box")
#define a47 NSLocalizedString(@"Failed to start authenticating. Please try again." , @"Authentication failed, tell user to try again")
#define a48 NSLocalizedString(@"Failed to connect to XMPP server. Please check your login credentials and internet connection and try again." , @"Message when cannot connect to XMPP server")
#define a49 NSLocalizedString(@"Domain needs to be set manually when specifying a custom port" , @"Message when port is changed but domain not set")
#define a50 NSLocalizedString(@"Logging in..." , @"shown during the login proceess")
#define a51 NSLocalizedString(@"You must enter a username and a password to login." , @"error message shown when user doesnt fill in a username or password")
#define a52 NSLocalizedString(@"Basic" , @"string to describe basic set of settings")
#define a53 NSLocalizedString(@"Advanced" , @"stirng to describe advanced set of settings")
#define a54 NSLocalizedString(@"SSL Hostname Mismatch" , @"stirng for settings to allow ssl mismatch")
#define a55 NSLocalizedString(@"Self Signed SSL" , @"string for settings to allow self signed ssl stirng")
#define a56 NSLocalizedString(@"Port" , @"Label for port number field for connecting to service")
#define a57 NSLocalizedString(@"user@gmail.com" , @"example of a google talk account")
#define a58 NSLocalizedString(@"Required" , @"String to let user know a certain field like a password is required to create an account")
#define a59 NSLocalizedString(@"Send Delivery Receipts" , @"String in login settings asking to send delivery receipts")
#define a60 NSLocalizedString(@"Send Typing Notificaction" , @"Stirng in login settings asking to send typing notification")
#define a61 NSLocalizedString(@"Log Out" , @"log out from account")
#define a62 NSLocalizedString(@"Log In" , @"log in to account")
#define a63 NSLocalizedString(@"Logout from OSCAR?" , @"Ask user if they want to logout of OSCAR")
#define a64 NSLocalizedString(@"Logout from XMPP?" , @"ask user if they want to log out of xmpp")
#define a65 NSLocalizedString(@"Delete Account?" , @"Ask user if they want to delete the stored account information")
#define a66 NSLocalizedString(@"Permanently delete" , @"Ask user if they want to delete the stored account information")
#define a67 NSLocalizedString(@"No Saved Accounts" , @"Message infomring user that there are no accounts currently saved")
#define a68 NSLocalizedString(@"ChatSecure is brought to you by many open source projects" , @"for attribution of other projects")
#define a69 NSLocalizedString(@"Check out the source here on Github" , @"let users know source is on Github")
#define a70 NSLocalizedString(@"Contribute a translation" , @"label for a link to contribute a new translation")
#define a71 NSLocalizedString(@"Project Homepage" , @"label for link to ChatSecure project website")
#define a72 NSLocalizedString(@"Version" , @"when displaying version numbers such as 1.0.0")
#define a73 NSLocalizedString(@"Username" , @"Label text for username field on login screen")
#define a74 NSLocalizedString(@"Password" , @"Label text for password field on login screen")
#define a75 NSLocalizedString(@"Domain" , @"Label text for domain field on login scree")
#define a76 NSLocalizedString(@"Login to" , @"Label for button describing which protocol you're logging into, will be followed by a protocol such as XMPP or AIM during layout")
#define a77 NSLocalizedString(@"Remember username" , @"label for switch for whether or not we should save their username between launches")
#define a78 NSLocalizedString(@"Remember password" , @"label for switch for whether or not we should save their password between launches")
#define a79 NSLocalizedString(@"Optional" , @"Hint text for domain field telling user this field is not required")
#define a80 NSLocalizedString(@"Your Facebook username is not the email address that you use to login to Facebook" , @"Text that makes it clear which username to use")
#define a81 NSLocalizedString(@"Send Crash Reports" , @"Title for crash reports settings switch")
#define a82 NSLocalizedString(@"Automatically send anonymous crash logs (opt-in)" , @"Description for crash reports settings switch")
#define a83 NSLocalizedString(@"Other" , @"Title for other miscellaneous settings group")
#define a84 NSLocalizedString(@"Self-Signed SSL" , @"Title for settings cell on whether or not the XMPP library should allow self-signed SSL certificates")
#define a85 NSLocalizedString(@"Hostname Mismatch" , @"Title for settings cell on whether or not the XMPP library should allow SSL hostname mismatch")
#define a86 NSLocalizedString(@"Warning: Use with caution! This may reduce your security." , @"Cell description text that warns users that enabling that option may reduce their security.")
#define a87 NSLocalizedString(@"Auto-delete" , @"Title for automatic conversation deletion setting")
#define a88 NSLocalizedString(@"Delete chats on disconnect" , @"Description for automatic conversation deletion")
#define a89 NSLocalizedString(@"Font Size" , @"Size for the font in the chat screen")
#define a90 NSLocalizedString(@"Size for font in chat view" , @"description for what the font size setting affects")
#define a91 NSLocalizedString(@"Signout Warning" , @"Title for setting about showing a warning before disconnection")
#define a92 NSLocalizedString(@"1 Minute Alert Before Disconnection" , @"Description for disconnection warning setting")
#define a93 NSLocalizedString(@"Default" , @"default string to revert to normal language behaviour")
#define a94 NSLocalizedString(@"Settings" , @"Title for the Settings screen")
#define a95 NSLocalizedString(@"Share" , @"Title for sharing a link to the app")
#define a96 NSLocalizedString(@"Not Available" , @"Shown when a feature is not available, for example SMS")
#define a97 NSLocalizedString(@"Chat with me securely" , @"Body of SMS or email when sharing a link to the app")
#define a98 NSLocalizedString(@"Connected" , @"Whether or not account is logged in")
#define a99 NSLocalizedString(@"Send Feedback" , @"String on button to email feedback")
#define a100 NSLocalizedString(@"Language" , @"string to bring up language selector")
#define a101 NSLocalizedString(@"Language Change" , @"Stirng of title to alert user langague is change")
#define a102 NSLocalizedString(@"In order to change langugages return to the home screen and remove ChatSecure from the recently used apps" , @"Message alerting user that they need to return to the home screen and force close ChatSecure")
#define a103 NSLocalizedString(@"Save" , @"Title for button for saving a setting")
#define a104 NSLocalizedString(@"New" , @"For a new settings value")
#define a105 NSLocalizedString(@"Old" , @"For an old settings value")
#define a106 NSLocalizedString(@"Done" , @"Title for button to press when user is finished")
#define a107 NSLocalizedString(@"This QR Code contains a link to http://omniqrcode.com/q/chatsecure and will redirect to the App Store." , @"Instructions label text underneath QR code")
#define a108 NSLocalizedString(@"Background session will expire in one minute." , @"Message displayed in Notification Manager when session will expire in one minute")
#define a109 NSLocalizedString(@"Read" , @"Title for action button on alert dialog, used as a verb in the present tense")
#define a110 NSLocalizedString(@"New Account" , @"Title for New Account View")
#define a111 NSLocalizedString(@"OSCAR Instant Messenger" , @"the name for AIM")
#define a112 NSLocalizedString(@"Google Talk" , @"the name for google talk")
#define a113 NSLocalizedString(@"Facebook" , @"the name for facebook")
#define a114 NSLocalizedString(@"Jabber (XMPP)" , @"the name for jabber, also include (XMPP) at the end")
#define a115 NSLocalizedString(@"Allow Plaintext Authentication" , @"Setting name for allowing authentication to happen in plain text or in the clear")
#define a116 NSLocalizedString(@"Require TLS" , @"Setting name for requiring a TLS connection")
#define a117 NSLocalizedString(@"Donate" , @"Title for donation link")
#define a118 NSLocalizedString(@"Your donation will help fund the continued development of ChatSecure." , @"Message shown when about to donate")
